// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sectors.Server.Data;

#nullable disable

namespace Sectors.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220209135157_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sectors.Shared.Models.UserSector", b =>
                {
                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SectorId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSectorsDb");

                    b.HasData(
                        new
                        {
                            SectorId = 576,
                            UserId = 1
                        },
                        new
                        {
                            SectorId = 25,
                            UserId = 1
                        },
                        new
                        {
                            SectorId = 37,
                            UserId = 2
                        },
                        new
                        {
                            SectorId = 267,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Sectors.Shared.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectorId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorId");

                    b.ToTable("SectorsDb");

                    b.HasData(
                        new
                        {
                            SectorId = 1,
                            Name = "Manufacturing"
                        },
                        new
                        {
                            SectorId = 19,
                            Name = "Construction materials"
                        },
                        new
                        {
                            SectorId = 18,
                            Name = "Electronics and Optics"
                        },
                        new
                        {
                            SectorId = 6,
                            Name = "Food and Beverage"
                        },
                        new
                        {
                            SectorId = 342,
                            Name = "Bakery & confectionery products"
                        },
                        new
                        {
                            SectorId = 43,
                            Name = "Beverages"
                        },
                        new
                        {
                            SectorId = 42,
                            Name = "Fish & fish products"
                        },
                        new
                        {
                            SectorId = 40,
                            Name = "Meat & meat products"
                        },
                        new
                        {
                            SectorId = 39,
                            Name = "Milk & dairy products"
                        },
                        new
                        {
                            SectorId = 437,
                            Name = "Other"
                        },
                        new
                        {
                            SectorId = 378,
                            Name = "Sweets & snack food"
                        },
                        new
                        {
                            SectorId = 13,
                            Name = "Furniture"
                        },
                        new
                        {
                            SectorId = 389,
                            Name = "Bathroom/sauna"
                        },
                        new
                        {
                            SectorId = 385,
                            Name = "Bedroom"
                        },
                        new
                        {
                            SectorId = 390,
                            Name = "Children’s room"
                        },
                        new
                        {
                            SectorId = 98,
                            Name = "Kitchen"
                        },
                        new
                        {
                            SectorId = 101,
                            Name = "Living room"
                        },
                        new
                        {
                            SectorId = 392,
                            Name = "Office"
                        },
                        new
                        {
                            SectorId = 394,
                            Name = "Other (Furniture)"
                        },
                        new
                        {
                            SectorId = 341,
                            Name = "Outdoor"
                        },
                        new
                        {
                            SectorId = 99,
                            Name = "Project furniture"
                        },
                        new
                        {
                            SectorId = 12,
                            Name = "Machinery"
                        },
                        new
                        {
                            SectorId = 94,
                            Name = "Machinery components"
                        },
                        new
                        {
                            SectorId = 91,
                            Name = "Machinery equipment/tools"
                        },
                        new
                        {
                            SectorId = 224,
                            Name = "Manufacture of machinery"
                        },
                        new
                        {
                            SectorId = 97,
                            Name = "Maritime"
                        },
                        new
                        {
                            SectorId = 271,
                            Name = "Aluminium and steel workboats"
                        },
                        new
                        {
                            SectorId = 269,
                            Name = "Boat/Yacht building"
                        },
                        new
                        {
                            SectorId = 230,
                            Name = "Ship repair and conversion"
                        },
                        new
                        {
                            SectorId = 93,
                            Name = "Metal structures"
                        },
                        new
                        {
                            SectorId = 508,
                            Name = "Other"
                        },
                        new
                        {
                            SectorId = 227,
                            Name = "Repair and maintenance service"
                        },
                        new
                        {
                            SectorId = 11,
                            Name = "Metalworking"
                        },
                        new
                        {
                            SectorId = 67,
                            Name = "Construction of metal structures"
                        },
                        new
                        {
                            SectorId = 263,
                            Name = "Houses and buildings"
                        },
                        new
                        {
                            SectorId = 267,
                            Name = "Metal products"
                        },
                        new
                        {
                            SectorId = 542,
                            Name = "Metal works"
                        },
                        new
                        {
                            SectorId = 75,
                            Name = "CNC-machining"
                        },
                        new
                        {
                            SectorId = 62,
                            Name = "Forgings, Fasteners"
                        },
                        new
                        {
                            SectorId = 69,
                            Name = "Gas, Plasma, Laser cutting"
                        },
                        new
                        {
                            SectorId = 66,
                            Name = "MIG, TIG, Aluminum welding"
                        },
                        new
                        {
                            SectorId = 9,
                            Name = "Plastic and Rubber"
                        },
                        new
                        {
                            SectorId = 54,
                            Name = "Packaging"
                        },
                        new
                        {
                            SectorId = 556,
                            Name = "Plastic goods"
                        },
                        new
                        {
                            SectorId = 559,
                            Name = "Plastic processing technology"
                        },
                        new
                        {
                            SectorId = 55,
                            Name = "Blowing"
                        },
                        new
                        {
                            SectorId = 57,
                            Name = "Moulding"
                        },
                        new
                        {
                            SectorId = 53,
                            Name = "Plastics welding and processing"
                        },
                        new
                        {
                            SectorId = 560,
                            Name = "Plastic profiles"
                        },
                        new
                        {
                            SectorId = 5,
                            Name = "Printing"
                        },
                        new
                        {
                            SectorId = 148,
                            Name = "Advertising"
                        },
                        new
                        {
                            SectorId = 150,
                            Name = "Book/Periodicals printing"
                        },
                        new
                        {
                            SectorId = 145,
                            Name = "Labelling and packaging printing"
                        },
                        new
                        {
                            SectorId = 7,
                            Name = "Textile and Clothing"
                        },
                        new
                        {
                            SectorId = 44,
                            Name = "Clothing"
                        },
                        new
                        {
                            SectorId = 45,
                            Name = "Textile"
                        },
                        new
                        {
                            SectorId = 8,
                            Name = "Wood"
                        },
                        new
                        {
                            SectorId = 337,
                            Name = "Other (Wood)"
                        },
                        new
                        {
                            SectorId = 51,
                            Name = "Wooden building materials"
                        },
                        new
                        {
                            SectorId = 47,
                            Name = "Wooden houses"
                        },
                        new
                        {
                            SectorId = 3,
                            Name = "Other"
                        },
                        new
                        {
                            SectorId = 37,
                            Name = "Creative industries"
                        },
                        new
                        {
                            SectorId = 29,
                            Name = "Energy technology"
                        },
                        new
                        {
                            SectorId = 33,
                            Name = "Environment"
                        },
                        new
                        {
                            SectorId = 2,
                            Name = "Service"
                        },
                        new
                        {
                            SectorId = 25,
                            Name = "Business services"
                        },
                        new
                        {
                            SectorId = 35,
                            Name = "Engineering"
                        },
                        new
                        {
                            SectorId = 28,
                            Name = "Information Technology and Telecommunications"
                        },
                        new
                        {
                            SectorId = 581,
                            Name = "Data processing, Web portals, E-marketing"
                        },
                        new
                        {
                            SectorId = 576,
                            Name = "Programming, Consultancy"
                        },
                        new
                        {
                            SectorId = 121,
                            Name = "Software, Hardware"
                        },
                        new
                        {
                            SectorId = 122,
                            Name = "Telecommunications"
                        },
                        new
                        {
                            SectorId = 22,
                            Name = "Tourism"
                        },
                        new
                        {
                            SectorId = 141,
                            Name = "Translation services"
                        },
                        new
                        {
                            SectorId = 21,
                            Name = "Transport and Logistics"
                        },
                        new
                        {
                            SectorId = 111,
                            Name = "Air"
                        },
                        new
                        {
                            SectorId = 114,
                            Name = "Rail"
                        },
                        new
                        {
                            SectorId = 112,
                            Name = "Road"
                        },
                        new
                        {
                            SectorId = 113,
                            Name = "Water"
                        });
                });

            modelBuilder.Entity("Sectors.Shared.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<bool>("Agreed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersDb");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Agreed = true,
                            Name = "TestPerson1"
                        },
                        new
                        {
                            UserId = 2,
                            Agreed = true,
                            Name = "TestPerson2"
                        });
                });

            modelBuilder.Entity("Sectors.Shared.Models.UserSector", b =>
                {
                    b.HasOne("Sectors.Shared.Sector", "Sector")
                        .WithMany("Users")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sectors.Shared.User", "User")
                        .WithMany("Sectors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sectors.Shared.Sector", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sectors.Shared.User", b =>
                {
                    b.Navigation("Sectors");
                });
#pragma warning restore 612, 618
        }
    }
}
